-- 구입목록 구입
-- 후원하기 누르면 INSERT되고 취소 누르면 STATUS를 N으로 확인 누르면 PROJECT금액 +

CREATE TABLE FUNDING(
    FUNDING_NO NUMBER PRIMARY KEY,
    FUNDING_CONTENT VARCHAR2(1000),
    FUNDING_PRICE NUMBER,
    FUNDING_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(FUNDING_STATUS IN('Y', 'N')),
    FUNDING_USER NUMBER NOT NULL,
    CONSTRAINT FK_FUNDING_USER FOREIGN KEY(FUNDING_USER) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_FUNDING_NO;

COMMENT ON COLUMN FUNDING."FUNDING_NO" IS '후원번호';
COMMENT ON COLUMN FUNDING."FUNDING_CONTENT" IS '후원내용';
COMMENT ON COLUMN FUNDING."FUNDING_PRICE" IS '후원가격';
COMMENT ON COLUMN FUNDING."FUNDING_STATUS" IS '후원상태';
COMMENT ON COLUMN FUNDING."FUNDING_USER" IS '후원회원번호';

INSERT INTO FUNDING VALUES(
    SEQ_FUNDING_NO.NEXTVAL, '후원TEST', 10000, DEFAULT, 1
);

COMMIT;









