-- SYSTEM �������� �����ؼ� ���ο� ���� ����
-- CREATE USER FD IDENTIFIED BY FD;
-- ���ο� ���� ����
-- GRANT RESOURCE, CONNECT TO FD;


----------------------------------------------------------
--------------------- USER ���� ���̺� ---------------------
----------------------------------------------------------

CREATE TABLE MEMBER (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(150),
    USER_ENROLL_DATE DATE DEFAULT SYSDATE,
    USER_MODIFY_DATE DATE DEFAULT SYSDATE,
    USER_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(USER_STATUS IN('Y', 'N')),
    USER_ROLE VARCHAR2(20) DEFAULT 'ROLE_USER',
    USER_COIN NUMBER DEFAULT 0
);


COMMENT ON COLUMN MEMBER.USER_NO IS 'ȸ����ȣ';
COMMENT ON COLUMN MEMBER.USER_ID IS 'ȸ��ID';
COMMENT ON COLUMN MEMBER.USER_PWD IS 'ȸ��PWD';
COMMENT ON COLUMN MEMBER.USER_NAME IS 'ȸ����';
COMMENT ON COLUMN MEMBER.PHONE IS '��ȭ��ȣ';
COMMENT ON COLUMN MEMBER.EMAIL IS '�̸���';
COMMENT ON COLUMN MEMBER.ADDRESS IS '�ּ�';
COMMENT ON COLUMN MEMBER.USER_ENROLL_DATE IS 'ȸ��������';
COMMENT ON COLUMN MEMBER.USER_MODIFY_DATE IS '����������';
COMMENT ON COLUMN MEMBER.USER_STATUS IS 'ȸ������(Y/N)';
COMMENT ON COLUMN MEMBER.USER_ROLE IS 'ȸ��Ÿ��';
COMMENT ON COLUMN MEMBER.USER_COIN IS 'ĳ���Ӵ�';

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL,'admin', '1234', '������', '010-1234-5678', 'admin@iei.or.kr', '����� ������', SYSDATE, SYSDATE, DEFAULT, 'ROLE_ADMIN', DEFAULT
);

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL, 'ismoon', '1234', '�Ϲ�ȸ��', '010-1111-2222', 'ismoon@iei.or.kr', '����� ���۱�', SYSDATE, SYSDATE, DEFAULT, DEFAULT, 100000
);

INSERT INTO MEMBER VALUES(
    SEQ_UNO.NEXTVAL, 'creator', '1234', 'â����', '010-3333-5555', 'creator@iei.or.kr', '����� ���ı�', SYSDATE, SYSDATE, DEFAULT, 'ROLE_CREATOR', DEFAULT
);

COMMIT;

-- ��� ��ȸ
-- SELECT * FROM MEMBER WHERE USER_ID=? AND USER_PWD=? AND USER_STATUS='Y'

-- ��� �߰�
-- INSERT INTO MEMBER VALUES(SEQ_UNO.NEXTVAL,?,?,?,?,?,?,SYSDATE,SYSDATE,DEFAULT,DEFAULT,DEFAULT)

-- ��� ã��
-- SELECT * FROM MEMBER WHERE USER_ID=?

-- ��� �н����� ����
-- UPDATE MEMBER SET PASSWORD=? WHERE USER_ID=?

-- ��� ����
-- UPDATE MEMBER SET USER_NAME=?,PHONE=?,EMAIL=?,ADDRESS=?,MODIFY_DATE=SYSDATE WHERE USER_ID=?

-- ��� ����
-- UPDATE MEMBER SET STATUS=? WHERE USER_ID=?

-- ��� â���ڷ� ����?
-- ��� ĳ���Ӵ� �� ����?


--------------------------------------------------------------------
---------------------- project test ���� ���̺� ----------------------
--------------------------------------------------------------------

-- �׽�Ʈ��
CREATE TABLE CARRYFUNDING_PROJECT(
    PROJECT_NO NUMBER PRIMARY KEY,
    PROJECT_TITLE VARCHAR2(200) NOT NULL,
    PROJECT_COMPANY VARCHAR2(100),
    TARGET_AMOUNT NUMBER NOT NULL,
    REACH_AMOUNT NUMBER NOT NULL,
    PROJECT_ENROLL_DATE DATE DEFAULT SYSDATE,
    PROJECT_MODIFY_DATE DATE DEFAULT SYSDATE,
    PROJECT_END_DATE DATE NOT NULL,
    IMG_NAME VARCHAR2(100),
    VIDEO_NAME VARCHAR2(100),
    PROJECT_CONTENT VARCHAR2(4000),
    PROJECT_CHECK VARCHAR2(1) DEFAULT 'N' CHECK (PROJECT_CHECK IN('Y', 'N')),
    PROJECT_COUNT NUMBER DEFAULT 0,
    PROJECT_LIKE NUMBER DEFAULT 0,
    PROJECT_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (PROJECT_STATUS IN('Y', 'N')),
    CREATOR_NO NUMBER NOT NULL,
    CONSTRAINT FK_PROJECT_WRITER FOREIGN KEY(CREATOR_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_PROJECT_NO;

COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_NO" IS '������Ʈ��ȣ';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_TITLE" IS '������Ʈ����';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_COMPANY" IS '��ü��';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."TARGET_AMOUNT" IS '��ǥ�ݾ�';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."REACH_AMOUNT" IS '���絵�ޱݾ�';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_ENROLL_DATE" IS '������Ʈ���۳�¥';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_MODIFY_DATE" IS '������Ʈ����������¥';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_END_DATE" IS '������Ʈ���ᳯ¥';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."IMG_NAME" IS '�̹�������̸�';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."VIDEO_NAME" IS '���������̸�';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_CONTENT" IS '������Ʈ����';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_CHECK" IS '������Ʈ�ɻ����';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_COUNT" IS '������Ʈ��ȸ��';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_LIKE" IS '���ƿ��ϼ�';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."PROJECT_STATUS" IS '������Ʈ����';
COMMENT ON COLUMN CARRYFUNDING_PROJECT."CREATOR_NO" IS 'â���ڹ�ȣ';

INSERT INTO CARRYFUNDING_PROJECT VALUES(
    SEQ_PROJECT_NO.NEXTVAL,
    '������ƮTEST',
    'CARRY',
    1000000,
    0,
    DEFAULT,
    DEFAULT,
    '21/01/25',
    '�̹���.JPG',
    '����.AVI',
    '������Ʈ TEST �Դϴ�. ���� ������ �־�� �ұ��? ���� ���͵� �������?
    �ٹٲ� �����͵� �����ؾ��ұ�? ����̳׿䤻����',
    'Y',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    1
);

INSERT INTO CARRYFUNDING_PROJECT VALUES(
    SEQ_PROJECT_NO.NEXTVAL,
    'TEST2',
    'ISMOON',
    10000000,
    0,
    DEFAULT,
    DEFAULT,
    '21/01/30',
    '�̹���1.JPG',
    '����1.AVI',
    '������Ʈ TEST222 �Դϴ�. ���� ������ �־�� �ұ��? ���� ���͵� �������?
    �ٹٲ� �����͵� �����ؾ��ұ�? ����̳׿䤻����',
    'Y',
    DEFAULT,
    DEFAULT,
    DEFAULT,
    2
);

-- ������Ʈ �� ��ȸ�ϱ�
--SELECT P.PROJECT_NO, P.PROJECT_TITLE, M.USER_ID, P.PROJECT_COMPANY, P.TARGET_AMOUNT, P.REACH_AMOUNT, P.PROJECT_ENROLL_DATE, P.PROJECT_MODIFY_DATE, P.PROJECT_END_DATE, P.IMG_NAME, P.VIDEO_NAME, P.PROJECT_CONTENT, P.PROJECT_COUNT, P.PROJECT_LIKE
--FROM CARRYFUNDING_PROJECT P
--JOIN MEMBER M ON(P.CREATOR_NO = M.USER_NO)
--WHERE P.PROJECT_STATUS = 'Y' AND P.PROJECT_CHECK = 'Y' AND P.PROJECT_NO = ?


--------------------------------------------------------------------
------------------------- Board ���� ���̺� --------------------------
--------------------------------------------------------------------






--------------------------------------------------------------------
------------------------- point ���� ���̺� --------------------------
------------- 2021/ 01/ 20 �̽� POINT ���� ���̺� �߰�(INSERTPOINTINFO)----------------

CREATE TABLE POINT_CHARGING (
    PAYMENT_NO NUMBER PRIMARY KEY,
    PAYMENT_AMOUNT NUMBER NOT NULL,
    PAYMENT_BANK_NAME VARCHAR2(30) NOT NULL,
    BANK_ACCOUNT_NUMBER NUMBER NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    CANCLE_PAYMENT_DATE DATE DEFAULT SYSDATE,
    PAYMENT_PROGRESS VARCHAR2(1) DEFAULT 'Y' CHECK (PAYMENT_PROGRESS IN('Y', 'N')),
    PAYER_NO NUMBER NOT NULL,
    CONSTRAINT FK_POINT_PAYER FOREIGN KEY(PAYER_NO) REFERENCES MEMBER(USER_NO) ON DELETE SET NULL
);

COMMENT ON COLUMN POINT_CHARGING.PAYMENT_NO IS '������ȣ';
COMMENT ON COLUMN POINT_CHARGING.PAYMENT_AMOUNT IS '�����ݾ�';
COMMENT ON COLUMN POINT_CHARGING.PAYMENT_BANK_NAME IS '���������';
COMMENT ON COLUMN POINT_CHARGING.BANK_ACCOUNT_NUMBER IS '���¹�ȣ';
COMMENT ON COLUMN POINT_CHARGING.PAYMENT_DATE IS '������¥';
COMMENT ON COLUMN POINT_CHARGING.CANCLE_PAYMENT_DATE IS '������ҳ�¥';
COMMENT ON COLUMN POINT_CHARGING.PAYMENT_PROGRESS IS '�����������';
COMMENT ON COLUMN POINT_CHARGING.PAYER_NO IS '�����ڹ�ȣ';

--DROP TABLE POINT_CHARGING;

CREATE SEQUENCE SEQ_PAYMENT_NO;

COMMIT;
-- POINT INSERT��
--INSERT INTO POINT_CHARGING VALUES(SEQ_PAYMENT_NO.NEXTVAL, 10000, '����', 1100000000, SYSDATE, NULL, 'Y', 1);

INSERT INTO POINT_CHARGING VALUES(SEQ_PAYMENT_NO.NEXTVAL, 10000, '국민', 1111111111, SYSDATE, NULL, 'Y', 2);


