-- 테스트 중 아직 생성하지 마세요~

CREATE TABLE REWORD(
    REWORD_NO NUMBER PRIMARY KEY,
    REWORD_NAME VARCHAR2(1000) NOT NULL,
    REWARD_PRICE NUMBER DEFAULT 0,
    PRO_NO NUMBER NOT NULL,
    CONSTRAINT FK_PROJECT_NO FOREIGN KEY(PRO_NO) REFERENCES MEMBER(PROJECT_NO) ON DELETE SET NULL
);

CREATE SEQUENCE SEQ_REWORD_NO;

COMMENT ON COLUMN REWORD."REWORD_NO" IS '리워드번호';
COMMENT ON COLUMN REWORD."REWORD_NAME" IS '리워드이름';
COMMENT ON COLUMN REWORD."REWARD_PRICE" IS '리워드가격';
COMMENT ON COLUMN REWORD."PRO_NO" IS '프로젝트번호';